[module]

[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/KaTeX/KaTeX"

[[module.imports.mounts]]
source = "."
target = "assets/vendor/katex"

[[module.imports.mounts]]
source = "fonts"
target = "static/assets/katex/fonts"
